### ISSUE TITLE
Shim `Array.flat` for Node <11

### ISSUE THREAD

**Issue by haydenbleasel** [tomorrowstudio/generator-gatsby#8]
```
$ yo gatsby
? Site name Test
? Site URL https://test.com
? Site description Test
? Site author Test
? Brand color #FFFFFF
? Extra features Netlify configuration, Starter CSS design system, CSS variables
 polyfill, Button component


events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: Object.keys(...).map(...).flat is not a function
    at module.exports.writing (/usr/local/lib/node_modules/generator-gatsby/generators/app/index.js:110:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-gatsby/node_modules/yeoman-generator/lib/index.js:402:23)
    at /usr/local/lib/node_modules/generator-gatsby/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/generator-gatsby/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/usr/local/lib/node_modules/generator-gatsby/node_modules/yeoman-generator/lib/index.js:403:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/usr/local/lib/node_modules/generator-gatsby/node_modules/yeoman-generator/lib/index.js:415:18)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by seaneking** [comment]
What node version are you on? `Array.flat` is supported in 11+, which is worse than I thought, might rewrite that bit / polyfill it with a `reduce`.

**Comment by haydenbleasel** [comment]
`v10.16.0`
